package ai.interview.middleware.service.storage;

import ai.interview.middleware.config.AppProperties;
import ai.interview.middleware.domain.enums.StorageType;
import ai.interview.middleware.exception.ResourceNotFoundException;
import ai.interview.middleware.exception.StorageException;
import jakarta.annotation.PostConstruct;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;

/**
 * Local-filesystem storage for development and Docker Compose.
 *
 * <p>Selected when {@code app.storage.type=local}. On Kubernetes this requires a volume that outlives
 * the pod; without one, an upload disappears on the next rollout, which is exactly the failure the
 * S3 backend exists to avoid. {@code values-prod.yaml} therefore sets {@code s3}.
 */
@Service
@ConditionalOnProperty(name = "app.storage.type", havingValue = "local", matchIfMissing = true)
public class LocalFileStorageService implements FileStorageService {

    private static final Logger log = LoggerFactory.getLogger(LocalFileStorageService.class);

    private final Path root;

    public LocalFileStorageService(AppProperties properties) {
        this.root = Path.of(properties.storage().local().root()).toAbsolutePath().normalize();
    }

    @PostConstruct
    void prepareRoot() {
        try {
            Files.createDirectories(root);
            if (!Files.isWritable(root)) {
                throw new StorageException("Storage root is not writable: " + root);
            }
            log.info("Local resume storage rooted at {}", root);
        } catch (IOException e) {
            throw new StorageException("Cannot create storage root " + root, e);
        }
    }

    @Override
    public StorageType storageType() {
        return StorageType.LOCAL;
    }

    @Override
    public StoredFile store(
            UUID candidateId, String originalFilename, String contentType, byte[] content) {
        String key = StorageKeyFactory.buildKey(candidateId, originalFilename);
        Path target = resolveWithinRoot(key);
        try {
            Files.createDirectories(target.getParent());
            Files.write(target, content);
            log.debug("Stored {} bytes at {}", content.length, target);
            return new StoredFile(
                    key, content.length, StorageKeyFactory.sha256Hex(content), StorageType.LOCAL);
        } catch (IOException e) {
            throw new StorageException("Failed to write resume to " + target, e);
        }
    }

    @Override
    public byte[] retrieve(String storageKey) {
        Path source = resolveWithinRoot(storageKey);
        if (!Files.exists(source)) {
            throw new ResourceNotFoundException("Stored file", storageKey);
        }
        try {
            return Files.readAllBytes(source);
        } catch (IOException e) {
            throw new StorageException("Failed to read resume from " + source, e);
        }
    }

    @Override
    public void delete(String storageKey) {
        Path target = resolveWithinRoot(storageKey);
        try {
            boolean deleted = Files.deleteIfExists(target);
            log.debug("Delete of {} -> {}", target, deleted ? "removed" : "already absent");
        } catch (IOException e) {
            throw new StorageException("Failed to delete resume at " + target, e);
        }
    }

    /**
     * Resolves a key under the root and refuses anything that escapes it.
     *
     * <p>Keys are generated by {@link StorageKeyFactory} today, but this method is the boundary a
     * stored key crosses on the way back from the database, so the check belongs here rather than at
     * the point of creation.
     */
    private Path resolveWithinRoot(String storageKey) {
        Path resolved = root.resolve(storageKey).normalize();
        if (!resolved.startsWith(root)) {
            throw new StorageException("Storage key escapes the storage root: " + storageKey);
        }
        return resolved;
    }

    /** Overwrites in place; used by the migration script when re-keying existing files. */
    void replace(String storageKey, byte[] content) {
        Path target = resolveWithinRoot(storageKey);
        try {
            Files.createDirectories(target.getParent());
            Path temp = Files.createTempFile(target.getParent(), "upload-", ".tmp");
            Files.write(temp, content);
            Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException e) {
            throw new StorageException("Failed to replace resume at " + target, e);
        }
    }
}
